import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ubaidullah",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="https://lh3.googleusercontent.com/a/ACg8ocLPx0pEzYBIxki07T1kZA7BIIAD7kFcmOSvQH2pzyqA4H-0qg3p=s120-c-no"
          type="image/jpeg"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
